### ISSUE TITLE
versions >= 3.4 do not run on Janelia Spark cluster with the below error message

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/n5-spark#16]
```
Classpath elements:
file:/groups/saalfeld/home/saalfelds/spark/n5-spark/target/n5-spark-3.4.2-SNAPSHOT-provided.jar


20/01/08 22:11:35 ERROR TransportRequestHandler: Error while invoking RpcHandler#receive() for one-way message.
org.apache.spark.SparkException: Could not find AppClient.
        at org.apache.spark.rpc.netty.Dispatcher.postMessage(Dispatcher.scala:160)
        at org.apache.spark.rpc.netty.Dispatcher.postOneWayMessage(Dispatcher.scala:140)
        at org.apache.spark.rpc.netty.NettyRpcHandler.receive(NettyRpcEnv.scala:655)
        at org.apache.spark.network.server.TransportRequestHandler.processOneWayMessage(TransportRequestHandler.java:208)
        at org.apache.spark.network.server.TransportRequestHandler.handle(TransportRequestHandler.java:113)
        at org.apache.spark.network.server.TransportChannelHandler.channelRead(TransportChannelHandler.java:118)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
...
```

**Comment by igorpisarev** [comment]
We've been able to run versions >= 3.4 on the cluster consistently without any issues, and the stack trace is a generic Spark connectivity error so this probably was a temporary glitch on the cluster.
